### ISSUE TITLE
if the thumbnail in the tibia wiki site is broken, the script wont continue

### ISSUE THREAD

**Issue by nokoji** [divinity76/YurOTSMonsterLibrary#2]

**Comment by divinity76** [comment]
i guess it throws some error? can you show me the error message? also, can you give the url to a "broken" wikia page? or what the script tried to process when it found the broken page?  was it an item? monster? what was the name?

**Comment by divinity76** [comment]
and the entire wiki spider is broken too, cba re-writing the wiki parser, so i made a bunch of static urls from ealier data.

fixed in 7e49e772863b67ad22bb4215b25555d4c3c336b1
